Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "ATLAS-HDMI"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/by-path/platform-axi:gpu-card"
EndSection

Section "Monitor"
    Identifier "TS7-Pro"
    Option "PreferredMode" "1024x600"
EndSection

Section "Screen"
    Identifier "ATLAS-HDMI-Screen"
    Device "ATLAS-HDMI"
    Monitor "TS7-Pro"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1024x600"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "ATLAS-Physical-Layout"
    Screen 0 "ATLAS-HDMI-Screen"
EndSection
