context.modules = [
    { name = libpipewire-module-echo-cancel
      args = {
          library.name  = aec/libspa-aec-webrtc
          node.latency  = 480/48000
          audio.rate    = 48000
          audio.channels = 1
          audio.position = [ MONO ]

          capture.props = {
              node.name          = "atlas_aec_capture"
              node.description   = "ATLAS AEC raw microphone input"
              target.object      = "alsa_input.usb-Jieli_Technology_UACDemoV1.0-00.mono-fallback"
              node.passive       = true
              node.dont-reconnect = false
          }
          source.props = {
              node.name        = "atlas_aec_source"
              node.description = "ATLAS AEC Microphone"
              media.class      = "Audio/Source"
          }
          sink.props = {
              node.name        = "atlas_aec_sink"
              node.description = "ATLAS AEC Voice Output"
              media.class      = "Audio/Sink"
          }
          playback.props = {
              node.name          = "atlas_aec_playback"
              node.description   = "ATLAS AEC HDMI playback"
              target.object      = "alsa_output.platform-107c701400.hdmi.hdmi-stereo"
              node.passive       = true
              node.dont-reconnect = false
          }
      }
    }
]
