[general]
fontname=DejaVu Sans Mono 16
bgcolor=#05070c
fgcolor=#dce8ff
bgalpha=65535
scrollback=5000
disallowbold=false
boldbright=true
cursorblinks=true
cursorunderline=false
audiblebell=false
visualbell=false
tabpos=top
geometry_columns=104
geometry_rows=30
hidescrollbar=true
hidemenubar=true
hideclosebutton=true
hidepointer=true
disablef10=true
disablealt=false
disableconfirm=true

[shortcut]
zoom_in_accel=<Primary>plus
zoom_out_accel=<Primary>minus
zoom_reset_accel=<Primary>0
