[Service]
ExecCondition=/usr/local/libexec/atlas-plymouth-poweroff screen-is-on
ExecStart=
ExecStart=/usr/sbin/plymouthd --mode=reboot --attach-to-session --tty=/dev/tty1 --graphical-boot --ignore-serial-consoles
ExecStartPost=
ExecStartPost=/usr/local/libexec/atlas-plymouth-poweroff
